<a href="https://colab.research.google.com/github/Introvert07/ml/blob/main/NLP_DATASCIENCE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
df = pd.read_csv('train.txt',sep = ';',header =None,names = ['text','emotion'])


In [3]:
df.head()

text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [5]:
df['emotion'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [6]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i=0
for emo in unique_emotions:
    emotion_numbers[emo] = i
    i+=1
df['emotion'] = df['emotion'].map(emotion_numbers)

In [7]:
df.head()

text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [8]:
df['text'] = df['text'].apply(lambda x :x.lower())

In [9]:
import string

def remove_punc(txt):
    txt = txt.translate(str.maketrans('','',string.punctuation))
    return txt

In [10]:
df['text'] = df['text'].apply(remove_punc)

In [11]:
def remove_numbers(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new = new+i
  return new
df['text'] = df['text'].apply(remove_numbers)

In [12]:
def remove_emojis(txt):
  new = ""
  for i in txt:
    if i.isascii():
          new += i
  return new
df['text'] = df['text'].apply(remove_emojis)

In [13]:
import nltk

In [14]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [15]:
stop_words = set(stopwords.words('english'))

In [16]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [17]:
len(stop_words)

198

In [18]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [19]:
def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

      return ''.join(cleaned)


In [20]:
df['text'] = df['text'].apply(remove)

In [21]:
df.loc[1]['text']

'go'

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
documents = [
    "I love Pizza",
    "Pizza is the best",
    "I love Pizza",
    "Pasta is great"
]
vectorizer = CountVectorizer(ngram_range=(2,2))
X = vectorizer.fit_transform(documents)


print("vocab:", vectorizer.get_feature_names_out())
print("\nBoW Matrix:\n", X.toarray())


vocab: ['is great' 'is the' 'love pizza' 'pasta is' 'pizza is' 'the best']

BoW Matrix:
 [[0 0 1 0 0 0]
 [0 1 0 0 1 1]
 [0 0 1 0 0 0]
 [1 0 0 1 0 0]]


In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
documents = [
    "I love Pizza",
    "Pizza is the best",
    "I love Pizza",
    "Pasta is great"
]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(documents)


print("vocab:", vectorizer.get_feature_names_out())
print("\nBoW Matrix:\n", X.toarray())


vocab: ['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']

BoW Matrix:
 [[0.         0.         0.         0.77722116 0.         0.62922751
  0.        ]
 [0.57457953 0.         0.4530051  0.         0.         0.36674667
  0.57457953]
 [0.         0.         0.         0.77722116 0.         0.62922751
  0.        ]
 [0.         0.61761437 0.48693426 0.         0.61761437 0.
  0.        ]]


In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.2, random_state=42)


In [34]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)


nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)


pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))

0.3265625


In [35]:
pred_bow

array([0, 5, 5, ..., 5, 0, 5])

In [36]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)


nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)


MultinomialNB()

In [37]:
y_pred = nb2_model.predict(X_test_tfidf)

In [38]:
print(accuracy_score(y_test,y_pred))

0.3265625


0.3265625


In [39]:
from sklearn.linear_model import LogisticRegression
logictic_model = LogisticRegression(max_iter=1000)
logictic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [40]:
log_pred = logictic_model.predict(X_test_tfidf)

In [41]:
print(accuracy_score(y_test,log_pred))

0.326875
